-- ⚠️ SCRIPT OBSOLETO - NÃO USAR ⚠️
--
-- Este script não funciona porque não é possível inserir diretamente na tabela auth.users
-- do Supabase. Use uma das alternativas abaixo:
--
-- OPÇÃO 1: Cadastrar pelo aplicativo (RECOMENDADO)
-- 1. Acesse o aplicativo e faça o primeiro cadastro
-- 2. O primeiro usuário será automaticamente definido como admin
--
-- OPÇÃO 2: Promover usuário existente a admin
-- 1. Cadastre-se normalmente no aplicativo
-- 2. Use o script 'promote_user_to_admin.sql' para promover seu usuário a admin
--
-- OPÇÃO 3: Criar manualmente no dashboard do Supabase
-- 1. Acesse: https://supabase.com/dashboard/project/[SEU_PROJECT_ID]/auth/users
-- 2. Clique em "Add user" e escolha "Create new user"
-- 3. Preencha email e senha
-- 4. Após criar, use 'promote_user_to_admin.sql' para promovê-lo a admin

-- Este script não deve ser executado
SELECT 'Este script está obsoleto. Leia os comentários acima para alternativas.' as mensagem;
